version: "4"

volumes:
    pocketpay-manager-db:
    pocketpay-manager-queue:

networks:
    pocketpay-manager-internal:
    pocketpay-manager-external:
        name: pocketpay-manager-external
        external: true
    pocketpay-notifyer-external:
        name: pocketpay-notifyer-external
        external: true

services:

    pocketpay-manager-webserver:
        image: dumptec/nginx:1.21.dev
        hostname: pocketpay-manager-webserver
        container_name: pocketpay-manager-webserver
        working_dir: /app
        user: "dump"
        networks:
            - pocketpay-manager-internal
            - pocketpay-manager-external
        restart: "on-failure"
        depends_on:
            - pocketpay-manager-api
        ports:
            - "82:8080"
        volumes:
            - ./pocket-manager:/app
            - ./docker/pocket-manager/nginx/dev.conf:/opt/bitnami/nginx/conf/server_blocks/default.conf:ro

    pocketpay-manager-api:
        image: dumptec/php-fpm:dev-8.2-latest
        hostname: pocketpay-manager-api
        container_name: pocketpay-manager-api
        working_dir: /app
        user: "dump"
        dns: 1.1.1.1
        ports:
            - "22002:22"
        extra_hosts:
            - "host.docker.internal:${PHPFPM_XDEBUG_HOST_IP}"
        networks:
            - pocketpay-manager-internal
            - pocketpay-notifyer-external
        restart: "on-failure"
        volumes:
            - ./pocket-manager:/app
            - ./docker/pocket-manager/php-fpm/php-xdebug.ini:/usr/local/etc/php/conf.d/xx-php-xdebug.ini
        env_file:
            - pocket-manager/.env
        depends_on:
            pocketpay-manager-database:
                condition: service_healthy

    pocketpay-manager-worker:
        image: dumptec/php-fpm:dev-8.2-latest
        hostname: pocketpay-manager-worker
        container_name: pocketpay-manager-worker
        working_dir: /app
        user: "dump"
        dns: 1.1.1.1
        networks:
            - pocketpay-manager-internal
            - pocketpay-notifyer-external
        restart: "on-failure"
        volumes:
            - ./pocket-manager:/app
        env_file:
            - pocket-manager/.env
        depends_on:
            - pocketpay-manager-queue
            - pocketpay-manager-database
                - condition=service_healthy

    pocketpay-manager-database:
        image: postgres:14
        hostname: pocketpay-manager-database
        container_name: pocketpay-manager-database
        environment:
            - POSTGRES_USER=${DB_USERNAME}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_DB=${DB_DATABASE}
            - PGDATA=/var/lib/postgresql/data/pgdata
            - PGTZ=${TIMEZONE}
        ports:
            - "5432:5432"
        networks:
            - pocketpay-manager-internal
        restart: "no"
        volumes:
            - pocketpay-manager-db:/var/lib/postgresql/data/pgdata
        healthcheck:
            test: ["CMD-SHELL", "pg_isready"]
            interval: 10s
            timeout: 5s
            retries: 5

    pocketpay-manager-queue:
        image: rabbitmq:3.12.2-management-alpine
        container_name: pocketpay-manager-queue
        hostname: pocketpay-manager-queue
        container_name: pocketpay-manager-queue
        restart: "on-failure"
        env_file:
            - pocket-manager/.env
        networks:
            - pocketpay-manager-internal
        ports:
            - "822:15672"
        healthcheck:
            test: rabbitmq-diagnostics -q ping
            interval: 30s
            timeout: 30s
            retries: 3
