version: "4"

volumes:
    pocketpay-notifyer-queue:

networks:
    pocketpay-notifyer-internal:
    pocketpay-notifyer-external:
        name: pocketpay-notifyer-external
        external: true

services:

    pocketpay-notifyer-webserver:
        image: dumptec/nginx:1.21.dev
        hostname: pocketpay-notifyer-webserver
        container_name: pocketpay-notifyer-webserver
        working_dir: /app
        user: "dump"
        networks:
            - pocketpay-notifyer-internal
            - pocketpay-notifyer-external
        restart: "on-failure"
        depends_on:
            - pocketpay-notifyer-api
        ports:
            - "83:8080"
        volumes:
            - ./pocket-notifyer:/app
            - ./docker/pocket-notifyer/nginx/dev.conf:/opt/bitnami/nginx/conf/server_blocks/default.conf:ro

    pocketpay-notifyer-api:
        image: dumptec/php-fpm:dev-8.2-latest
        hostname: pocketpay-notifyer-api
        container_name: pocketpay-notifyer-api
        working_dir: /app
        user: "dump"
        dns: 1.1.1.1
        ports:
            - "22003:22"
        extra_hosts:
            - "host.docker.internal:${PHPFPM_XDEBUG_HOST_IP}"
        networks:
            - pocketpay-notifyer-internal
        restart: "on-failure"
        volumes:
            - ./pocket-notifyer:/app
        depends_on:
            - pocketpay-notifyer-queue
        env_file:
            - pocket-notifyer/.env

    pocketpay-notifyer-worker:
        image: dumptec/php-fpm:dev-8.2-latest
        hostname: pocketpay-notifyer-worker
        container_name: pocketpay-notifyer-worker
        working_dir: /app
        user: "dump"
        dns: 1.1.1.1
        ports:
            - "22033:22"
        extra_hosts:
            - "host.docker.internal:${PHPFPM_XDEBUG_HOST_IP}"
        networks:
            - pocketpay-notifyer-internal
        restart: "on-failure"
        volumes:
            - ./pocket-notifyer:/app
        depends_on:
            - pocketpay-notifyer-queue
        env_file:
            - pocket-notifyer/.env

    pocketpay-notifyer-queue:
        image: bitnami/redis
        hostname: pocketpay-notifyer-queue
        container_name: pocketpay-notifyer-queue
        networks:
            - pocketpay-notifyer-internal
        restart: "on-failure"
        volumes:
            - pocketpay-notifyer-queue:/bitnami/redis/data
        environment:
            - ALLOW_EMPTY_PASSWORD=no
            - REDIS_PASSWORD=${REDIS_PASSWORD}
            - TZ=${TIMEZONE}

    pocketpay-notifyer-redisadmin:
        image: erikdubbelboer/phpredisadmin
        hostname: pocketpay-notifyer-redisadmin
        container_name: pocketpay-notifyer-redisadmin
        environment:
            - REDIS_1_HOST=pocketpay-notifyer-queue
            - REDIS_1_PORT=6379
            - REDIS_1_AUTH=${REDIS_PASSWORD}
        networks:
            - pocketpay-notifyer-internal
        restart: "on-failure"
        ports:
            - 833:80
        depends_on:
            - pocketpay-notifyer-queue

    pocketpay-notifyer-mailhog:
        image: mailhog/mailhog
        hostname: pocketpay-notifyer-mailhog
        container_name: pocketpay-notifyer-mailhog
        restart: "on-failure"
        networks:
            - pocketpay-notifyer-internal
        ports:
            - ${MAILHOG_WEB_SMTP}:1025
            - ${MAILHOG_WEB_PORT}:8025