### Get balance of customer's pocket
GET {{ host_wallet_manager }}/api/balance/{{ wallet_manager_person_id }}/{{ wallet_manager_wallet_id }}

### Get customer transaction detail
GET {{ host_wallet_manager }}/api/transaction/{{ wallet_manager_transaction_id }}

### Get customer transaction history
GET {{ host_wallet_manager }}/api/transaction/history/{{ wallet_manager_person_id }}/{{ wallet_manager_wallet_id }}

### Transfer funds between customer's wallets
POST {{ host_wallet_manager }}/api/transaction
Content-Type: application/json
{
    "from_wallet": "a9d4a0ce-b310-4410-ad88-7243bd4f442f",
    "to_wallet": "55fd5695-1860-4a22-adeb-f149877c733d",
    "value": 150
}

### Create a customer wallet
POST {{ host_wallet_manager }}/api/wallet
Content-Type: application/json
{
    "person": "{{ wallet_manager_person_id }}"
}

### Set a client wallet as main
PATCH {{ host_wallet_manager }}/api/wallet/main/a9d4a0ce-b310-4410-ad88-7243bd4f442f
Content-Type: application/json

### get a main wallet's client
GET {{ host_wallet_manager }}/api/wallet/main/person/{{ wallet_manager_person_id }}
Content-Type: application/json

### get all client's wallet
GET {{ host_wallet_manager }}/api/wallet/all/person/{{ wallet_manager_person_id }}
Content-Type: application/json

### Add funds to client wallet
PATCH {{ host_wallet_manager }}/api/wallet/funds/aff4ea3b-96fd-401d-b577-42051872dbcb/150
Content-Type: application/json
